### ISSUE TITLE
ESC reboots at low to moderate velocities

### ISSUE THREAD

**Issue by nbbrooks** [platypusllc/lutra#8]
Reproducible causes using phone or laptop teleoperation window:
Gradually increase velocity to both ESCs to 0.2: cutout will occur after ~10 seconds
Gradually increase velocity to both or one ESC: cutout will occur around 0.3 
Very quickly move velocity to both ESCs: cutout will occur almost instantly.

Effects: One or both ESCs reboot, stopping the corresponding motor(s)
For Seaking ESCs, this results in beep tones corresponding to throttle related error codes or the beeps for the arming sequence codes, or the beeps for entering program mode. Which happens depends on how you manipulate the velocities being sent to the ESCs once the motors stop moving (and, presumably, the ESC has rebooted).

**Comment by christomaszewski** [comment]
I don't think this is a problem any longer with the newest software and the dynamite ESCs

**Comment by psigen** [comment]
Ok, we'll reopen if we start to see this again.
